######################################################################
# match unison exactly

resolver: lts-14.7
allow-newer: true
extra-deps:
  ######################################################################
  # additional deps

  # The latest
  - git: git@github.com:pkamenarsky/concur-replica
    commit: 'd282c20eeabcab4ef265f44622f784d8c50ab1f4'

  # The latest:
  - git: https://github.com/pkamenarsky/replica.git
    commit: 46d2fd3b2c236d573f1d6002eb58cc95b2ba03b9
  - git: https://github.com/pkamenarsky/concur.git
    commit: dc5347b35c79654d58fa95716f425ee7248504fb
    subdirs:
    - concur-core